name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@cf31444e770b9919bb21e695d66f56c39cfd3dee # main
      - run: brew test-bot --only-tap-syntax

  build:
    needs: syntax
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build.yml
    with:
      formula: jdx-ruby@3.4.1

  # This job is used as a required status check
  final:
    needs:
      - syntax
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    steps:
      - name: Check CI job results
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
